import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import MainSidebar from '../components/MainSidebar';
import { ToastProvider } from "../components/ToastProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function WidgetLayout({ children }) {
  return (
    <div>
        <ToastProvider>
          <MainSidebar />
          <main className="flex-1 sm:ml-64">{children}</main>
        </ToastProvider>
    </div>
  );
}
