import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainSidebar from './components/MainSidebar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="cs">
      <body className="bg-gray-900 text-gray-100 min-h-screen">
        <MainSidebar />
        <main className="flex-1 sm:ml-64">{children}</main>
      </body>
    </html>
  );
}
